version: '3.8'
services:
  frontend:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
      - NODE_ENV=development
   volumes:
     - ./frontend/:/usr/src/app
   command: sh -c "npm run start"
   ports:
     - "3000:3000"
   tty: true